import React, { Component } from 'react'
import { Button, Modal } from 'react-bootstrap';
import toc from '../server/toc.html';

export const TOC = ({showTerms, handleClose}) => {
    return(
        <div>
            <Modal show={showTerms}>
                <Modal.Footer>
                    <div className="toc">
                        <h3>LONGO’S TERMS OF USE FOR MOBILE APPLICATION</h3>
                        <strong>General Conditions</strong>
                        <p>Please review these Terms of Use prior to using the mobile application and associated services for bakery orders online (the “Services”), as you are deemed to accept and be bound by these Terms of Use in accessing any of the Services.</p>
                        <p>Longo Brothers Fruit Markets Inc. ("Longo’s") reserves the right to change these Terms of Use, in whole or in part, at any time without notice. Accordingly, you should always review this page prior to accessing any of the Services in order to ensure that you have an understanding of the current Terms of Use.</p>
                        <p>Should you disagree in any manner with these Terms of Use, you are required to immediately discontinue your use of the Services.</p>
                        <strong>Registration</strong>
                        <p>When registering for an account, you agree to provide accurate and current information about yourself as requested and to promptly update such information as necessary to ensure that it is kept accurate and complete. You agree to be responsible for: (a) the accuracy of all information that you provide to us; (b) maintaining the confidentiality of any passwords or other account identifiers that you choose or that are otherwise assigned to you as a result of any registration or purchase made through the application; and (c) all activities that occur under such password(s) or account(s). Further, you agree to notify us of any unauthorized use of your password or account of which you are or become aware of. Longo’s shall not be responsible or liable, directly or indirectly, in any way for any loss or damage of any kind incurred as a result of, or in connection with, your failure to comply with this section, or for any delay in shutting down your account after you have reported a breach of security to us.</p>
                        <strong>Placing an Order</strong>
                        <p>All dollar amounts are in Canadian dollars.</p>
                        <p>By completing the checkout and submitting an order through the mobile application, you are agreeing to pay, in full, the prices of the items selected and all applicable taxes, either by credit card or other permitted payment method.</p>
                        <p>In order to complete an order, you may be required to provide certain additional information that is required to process your order. If you do not complete or improperly complete your order, it may not be accepted or acknowledged. We reserve the right to change the permitted methods of payment at any time.</p>
                        <p>During the authorization process when you submit your order, your card is validated and must have enough available funds for the transaction to be approved. Upon approval, the order will be prepared for pickup. If you fail to pay any fees or charges when due, we reserve the right to charge such amount directly to the credit card as provided by you at the time you submitted your order. You are responsible and liable for any fees, including legal costs and collection costs, that we may incur in its efforts to collect any unpaid balances from you.</p>
                        <p>You may cancel your order or modify the order (including adding or removing products, changing quantities, or changing order pickup details) via mobile app up until the day prior to the pickup date selected (the “Cut-off time”).</p>
                        <p>If you try to make any modifications after the Cut-off Time, we cannot guarantee that the modification will be made prior to pickup date.</p>
                        <strong>Intended Use and Restrictions</strong>
                        <p>The material and Services is owned or licensed by Longo’s and is intended to be viewed by users in Ontario only. As the websites are business and commercial sites, access to the websites is not intended for use and may not be legally accessed by persons under the age of sixteen (16) years old.</p>
                        <p>Subject to the Longo’s Privacy Policy that restricts the use of personal data, any material, information or ideas that you as a user transmit or post on the mobile application by any means whatsoever will be treated as non-confidential and non-proprietary, and may be disseminated or used by Longo’s for any purpose it deems appropriate.</p>
                        <p>Users accessing the Services are advised that it is prohibited to post or transmit on or via the Services any unlawful, threatening, libelous, defamatory, scandalous, inflammatory, obscene, pornographic or profane material or any material that could constitute or encourage conduct that could be considered a criminal offense or violation of any law.</p>
                        <strong>Copyright</strong>
                        <p>Longo’s or the entity from which Longo’s licenses copyrighted material is the copyright owner of the mobile application design, text and graphics, and the selection and arrangement of such elements as part of the Services. Any reproduction, distribution, republication, posting, or transmission of the Services in any form or by any means without the express prior written approval of Longo’s and/or the licensee is strictly prohibited.</p>
                        <p>Longo’s grants to you as a user of the Services permission to lawfully access and use the Services available on the mobile application for personal use only, provided that you do not modify the materials. Users are strictly prohibited from selling any downloaded, archived or printed portions of the mobile application viewed.</p>
                        <p>Longo’s permission to you terminates automatically, without any need of notification of such termination, if you breach any of these Terms of Use.</p>
                        <strong>Trademarks</strong>
                        <p>All custom graphics and button icons are service marks and/or trademarks owned by Longo’s. In addition, there are numerous other trademarks, product names, company names, logo service and marks indicated in the mobile application that are the property of their respective owners and are displayed by Longo’s under license therefrom. You are prohibited from using any trademarked materials without the express prior written permission of Longo’s and/or the licensor.</p>
                        <strong>Warranties Related to the Use of the Mobile Application and Services</strong>
                        <p>Subject to the Longo’s return of goods policy, the information, materials and services contained on <a href="http://www.longos.com/">longos.com</a> website and/or mobile application, including but not limited to, the graphics, links and other items, are being provided to you on an "as is” and “as available” basis with no warranty. Longo’s does not warrant or guarantee the accuracy, adequacy or completeness of this information and materials, and expressly disclaims liability for any errors and/or omissions in this information and materials. To the maximum extent permitted by law, Longo’s disclaims all representations and warranties of any kind, whether expressed, implied or statutory, including, without limitation, the implied warranties of title, non-infringement, merchantability, and fitness for a particular purpose.</p>
                        <p>As well, Longo’s does not warrant, guarantee or make any representations whatsoever regarding the security of accounts, or that the mobile application or site is free from destructive materials including, but not limited to, computer viruses, hackers, or other technical sabotage. Further, Longo’s does not warrant, guarantee or make any representations that access to the <a href="http://www.longos.com/">longos.com</a> website or mobile application will be fully accessible, current and/or accurate at all times, uninterrupted, or error-free. You acknowledge and accept that your use of the website or mobile application is at your sole and entire risk.</p>
                        <p>Items listed may not be available or in-stock at all times for purchase on the mobile application. Longo’s reserves the right to correct, at any time, any pricing errors. While the mobile application is updated regularly, prices, selection and availability, including the availability of promotional offers, may vary and are subject to change without notice. Longo’s will not be responsible for any loss or damages arising from such updates or changes.</p>
                        <p>Without limiting the generality of the forgoing, Longo’s disclaims any and all warranties and conditions - express or otherwise - for, nor shall Longo’s be held responsible for the quality of, any merchandise displayed on <a href="http://www.longos.com/">longos.com</a> website or the mobile application. </p>
                        <strong>Promotions</strong>
                        <p>We may make various promotional offers from time to time on the mobile application. Some offers may be informational, web-based only and not available as an in-store offer or promotion. Not all offers and/or promotions available in store may be available on the mobile application. We ask that you review the guidelines associated with each special offer, as they will differ.</p>
                        <p>If you redeem any coupon, Thank You Rewards points or gift cards, this will be reflected at checkout and is subject to validation and any redemption requirements. Manufacturers’ coupons and warranties are the responsibility of the individual manufactures. Coupons offered by the manufacturers may each have relevant information about the duration and limitations of the coupon.</p>
                        <p>For any of our coupons, in the event we have inadvertently made a typographical error on any coupon or special offer, we reserve the right to suspend redemption or terminate altogether the coupon or offer.</p>
                        <p>We may also offer our customers the opportunity to participate in contests, sweepstakes or other promotions as decided by us. In each case, the promotion may have additional terms and conditions which apply in addition to these terms and conditions. Please review the terms and conditions associated with the particular promotion to determine your eligibility and any participation requirements.</p>
                        <strong>Indemnification</strong>
                        <p>By accessing any of the Services, you agree to defend, indemnify and hold Longo’s harmless from and against any and all loss, actions, claims, damages, costs and expenses, including legal fees and disbursements on a full indemnity basis, arising from or related to your use of the mobile application or longos.com website or any breach of this Agreement. This provision shall survive the termination of this Agreement and remain in full force and effect.</p>
                        <strong>Limitation of Liability</strong>
                        <p>By accessing any of the Services, you acknowledge, accept and agree that in no event shall Longo’s be liable for any damages, including without limitation any and all direct or indirect, special, incidental, compensatory, exemplary or consequential damages, losses or expenses, including without limitation lost or misdirected orders, lost profits, lost registrations, lost goodwill, or lost or stolen programs or other data, howsoever caused and under any theory of liability arising out of or in connection with (1) the use of the mobile application; (2) any failure or performance, error, omission, interruption, defect, delay in operation or transmission; and/or (3) line or system failure or the introduction of a computer virus, or other technical sabotage, even if Longo’s, its employees or representatives thereof, are advised of the possibility or likelihood of such damages, losses or expenses.</p>
                        <strong>General Terms</strong>
                        <p>Longo’s reserves the right to correct any inaccuracies or typographical errors in the information posted on the mobile application, and shall have no liability for such errors. Information may be changed or updated without notice and prices and availability of goods and services are subject to change without notice.</p>
                        <p>In the event that any provision(s) contained within these Terms of Use is/are held to be invalid or unenforceable for any reason, such invalidity or unenforceability shall not affect the remainder of these Terms of Use, and these Terms of Use shall be construed and enforced as if the invalid or unenforceable term(s) or provision(s) had not been included in these Terms of Use.</p>
                        <p>Longo's failure to insist upon or enforce strict performance of any term(s) or provision(s) contained herein shall not be construed as a waiver of any term, provision, right or obligation.</p>
                        <p>Longo’s has taken reasonable steps to ensure that the mobile application and <a href="http://www.longos.com/">longos.com</a> website are WCAG 2.0 Level A compliant at the present time and shall be WCAG 2.0 Level AA compliant by January 1, 2021.</p>
                        <p>These Terms of Use constitutes the entire agreement between Longo’s and you and govern your use of the Services, superseding any prior agreements between Longo’s and you (including, but not limited to, any prior versions of the Terms of Use).</p>
                        <Button onClick={handleClose}>Close</Button>
                    </div>
                </Modal.Footer>
            </Modal>
        </div>
    )
}